language: python
python: '2.7'
script: py.test
deploy:
  provider: pypi
  user: iml
  password:
    secure: SwBPbbuaCL6wARzaKK2Iuc4i1SFN9vvNvHnT79hypSTj4uE8rsVvUI2EbP+sN89VmOLIlOGRBEh3FpFZx53m79VYfGh3Bk+FAtyco7OSdBceAp6HDvvXLy6lwByuhNFljfNbYqCbRv0uY1eW7iyY8H1UT0zhcwGddc+14zhL09glPCMYAnsFzQZZUlpxL9k7I4h8VIgOW28VPz/tUSyu/6jD31CLcEhu327SxWeTcggeFtB99FM3D6AxJovbjGgEworXX79JoEgScu+p3OYj65Fp7orL6aScELJWJaxFnH3j2Y8I7cnwiHeW2cGs45NskmPoCOKfBInCxqOhkDArCjbFvMHiWqQHvqO/q87eKJHx4MC2RugG8XHevP9Hk8j5wGFZhOhTXEnave+EwBeb2U9DoN8W9RgAuiHb2PRbEB0zEd45waiubYHsGSR9jF6D20sDhcrqKKYJVaphmNxuFClbHUxIwHX+Zt1X3Bm91wdli1Ul9ZEq+RRzdnzanrUTbC52tOa7PKq5q8fweytaFqLcLTj+MzmY5mJHRozld9B9jxLqNV8hTYXzICCksmk5keE0QYYprBUjN9OcTKgG12pfeV6U5wMG0Fo2nGML0aGSp4CkB4laMKgKT0lhEBhUxR5u0ANeJeO7Rky/f0NcDiHNozsL+goGT2+omRaaid4=
  on:
    tags: true
